{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/15747",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/15747/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/15747/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/15747/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/15747",
    "id": 2296233687,
    "node_id": "I_kwDOBWUGps6I3b7X",
    "number": 15747,
    "title": "[BUG] cudf.pandas dataframe.__repr__ slow in jupyterlab for large datasets",
    "user": {
        "login": "AjayThorve",
        "id": 20476096,
        "node_id": "MDQ6VXNlcjIwNDc2MDk2",
        "avatar_url": "https://avatars.githubusercontent.com/u/20476096?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AjayThorve",
        "html_url": "https://github.com/AjayThorve",
        "followers_url": "https://api.github.com/users/AjayThorve/followers",
        "following_url": "https://api.github.com/users/AjayThorve/following{/other_user}",
        "gists_url": "https://api.github.com/users/AjayThorve/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AjayThorve/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AjayThorve/subscriptions",
        "organizations_url": "https://api.github.com/users/AjayThorve/orgs",
        "repos_url": "https://api.github.com/users/AjayThorve/repos",
        "events_url": "https://api.github.com/users/AjayThorve/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AjayThorve/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-05-14T19:23:17Z",
    "updated_at": "2024-05-19T03:50:06Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nCalling a dataframe.__repr__ in a notebook cell either takes very long or results in a kernel failure for large datasets. \r\n**Steps/Code to reproduce bug**\r\nIn a jupyterlab environment, run this in a cell:\r\n\r\n```python\r\n\r\n# [cell 1]\r\n%load_ext cudf.pandas\r\n\r\n# [cell 2]\r\nimport pandas as pd\r\nimport numpy as np\r\n\r\n# Define the number of rows and columns\r\nnum_rows = 25_000_000\r\nnum_columns = 12\r\n\r\n# Create a DataFrame with random data\r\ndf = pd.DataFrame(np.random.randint(0, 100, size=(num_rows, num_columns)),\r\n                  columns=[f'Column_{i}' for i in range(1, num_columns + 1)])\r\n\r\n\r\n# [cell 3]\r\ndf\r\n```\r\n![image](https://github.com/rapidsai/cudf/assets/20476096/f496473d-369a-4fe4-a91c-950944b44c05)\r\n\r\n\r\n**Expected behavior**\r\ndataframe should render quickly, as is the case when working directly with cudf, or pandas\r\n\r\n**Note**\r\nThis works as expected in a python interactive shell, or when calling `print(df)` in a notebook.",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/15747/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/15747/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}