{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/13734",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/13734/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/13734/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/13734/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/13734",
    "id": 1816899003,
    "node_id": "I_kwDOBWUGps5sS627",
    "number": 13734,
    "title": "[BUG] `cudf.read_text` throws an exception when reading a host buffer",
    "user": {
        "login": "GregoryKimball",
        "id": 12725111,
        "node_id": "MDQ6VXNlcjEyNzI1MTEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/12725111?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/GregoryKimball",
        "html_url": "https://github.com/GregoryKimball",
        "followers_url": "https://api.github.com/users/GregoryKimball/followers",
        "following_url": "https://api.github.com/users/GregoryKimball/following{/other_user}",
        "gists_url": "https://api.github.com/users/GregoryKimball/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/GregoryKimball/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/GregoryKimball/subscriptions",
        "organizations_url": "https://api.github.com/users/GregoryKimball/orgs",
        "repos_url": "https://api.github.com/users/GregoryKimball/repos",
        "events_url": "https://api.github.com/users/GregoryKimball/events{/privacy}",
        "received_events_url": "https://api.github.com/users/GregoryKimball/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1013987352,
            "node_id": "MDU6TGFiZWwxMDEzOTg3MzUy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/0%20-%20Backlog",
            "name": "0 - Backlog",
            "color": "d4c5f9",
            "default": false,
            "description": "In queue waiting for assignment"
        },
        {
            "id": 1016332948,
            "node_id": "MDU6TGFiZWwxMDE2MzMyOTQ4",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/good%20first%20issue",
            "name": "good first issue",
            "color": "7057ff",
            "default": true,
            "description": "Good for newcomers"
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        },
        {
            "id": 1185244142,
            "node_id": "MDU6TGFiZWwxMTg1MjQ0MTQy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/cuIO",
            "name": "cuIO",
            "color": "fef2c0",
            "default": false,
            "description": "cuIO issue"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2023-07-22T21:20:47Z",
    "updated_at": "2024-04-13T05:23:04Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\n`cudf.read_text` throws an exception when reading a host buffer, unlike the CSV, Parquet, ORC and JSON readers. Hopefully it is straightforward to enable `cudf.read_text` to read from host buffers. \r\n\r\n**Steps/Code to reproduce bug**\r\nHere is a small code snippet that shows the exception:\r\n```\r\nfrom io import BytesIO\r\nimport cudf\r\n\r\ndf = cudf.DataFrame({'a':['aaaa','bbbb']})\r\n\r\nbuf = BytesIO()\r\ndf.to_csv(buf, index=False)\r\ndf2 = cudf.read_csv(buf) # this is ok\r\nprint(df2)\r\n\r\nbuf = BytesIO()\r\ndf.to_csv(buf, index=False)\r\ndf2 = cudf.read_text(buf, delimiter='\\n') # this crashes\r\nprint(df2)\r\n```\r\n\r\n**Expected behavior**\r\nI expect that `read_text` would support host buffers correctly in the python layer. \"multibyte_split\" works fine with HOST_BUFFER data source in the libcudf benchmarks.\r\n\r\n**Environment overview (please complete the following information)**\r\nnightly docker image from 23.08, A100 DGX workstation\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/13734/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/13734/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}