{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/6040",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/6040/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/6040/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/6040/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/6040",
    "id": 681863685,
    "node_id": "MDU6SXNzdWU2ODE4NjM2ODU=",
    "number": 6040,
    "title": "[BUG] Series.equals() raises error with ListColumns, while DataFrame.equals() works",
    "user": {
        "login": "miguelusque",
        "id": 26169771,
        "node_id": "MDQ6VXNlcjI2MTY5Nzcx",
        "avatar_url": "https://avatars.githubusercontent.com/u/26169771?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/miguelusque",
        "html_url": "https://github.com/miguelusque",
        "followers_url": "https://api.github.com/users/miguelusque/followers",
        "following_url": "https://api.github.com/users/miguelusque/following{/other_user}",
        "gists_url": "https://api.github.com/users/miguelusque/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/miguelusque/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/miguelusque/subscriptions",
        "organizations_url": "https://api.github.com/users/miguelusque/orgs",
        "repos_url": "https://api.github.com/users/miguelusque/repos",
        "events_url": "https://api.github.com/users/miguelusque/events{/privacy}",
        "received_events_url": "https://api.github.com/users/miguelusque/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": {
        "url": "https://api.github.com/repos/rapidsai/cudf/milestones/2",
        "html_url": "https://github.com/rapidsai/cudf/milestone/2",
        "labels_url": "https://api.github.com/repos/rapidsai/cudf/milestones/2/labels",
        "id": 6946310,
        "node_id": "MDk6TWlsZXN0b25lNjk0NjMxMA==",
        "number": 2,
        "title": "List and Struct data types and operations",
        "description": "",
        "creator": {
            "login": "beckernick",
            "id": 8457388,
            "node_id": "MDQ6VXNlcjg0NTczODg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8457388?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/beckernick",
            "html_url": "https://github.com/beckernick",
            "followers_url": "https://api.github.com/users/beckernick/followers",
            "following_url": "https://api.github.com/users/beckernick/following{/other_user}",
            "gists_url": "https://api.github.com/users/beckernick/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/beckernick/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/beckernick/subscriptions",
            "organizations_url": "https://api.github.com/users/beckernick/orgs",
            "repos_url": "https://api.github.com/users/beckernick/repos",
            "events_url": "https://api.github.com/users/beckernick/events{/privacy}",
            "received_events_url": "https://api.github.com/users/beckernick/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 19,
        "closed_issues": 49,
        "state": "open",
        "created_at": "2021-07-14T18:07:53Z",
        "updated_at": "2024-05-15T19:11:54Z",
        "due_on": null,
        "closed_at": null
    },
    "comments": 5,
    "created_at": "2020-08-19T13:58:55Z",
    "updated_at": "2023-07-31T08:52:57Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nWhen trying to compare two Series with ListColumns, the following error is displayed:\r\n\r\n```\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-11-6bd0d51bd16c> in <module>\r\n      4 series2 = cudf.Series({1: [10, 20, 30]})\r\n      5 \r\n----> 6 series1.equals(series2)\r\n\r\n/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/series.py in equals(self, other)\r\n   1499         if other is None or len(self) != len(other):\r\n   1500             return False\r\n-> 1501         return self._binaryop(other, \"eq\").min()\r\n   1502 \r\n   1503     def ne(self, other, fill_value=None, axis=0):\r\n\r\n/opt/conda/envs/rapids/lib/python3.7/contextlib.py in inner(*args, **kwds)\r\n     72         def inner(*args, **kwds):\r\n     73             with self._recreate_cm():\r\n---> 74                 return func(*args, **kwds)\r\n     75         return inner\r\n     76 \r\n\r\n/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/series.py in _binaryop(self, other, fn, fill_value, reflect)\r\n   1081                     rhs = rhs.fillna(fill_value)\r\n   1082 \r\n-> 1083         outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)\r\n   1084         result = lhs._copy_construct(data=outcol, name=result_name)\r\n   1085         return result\r\n\r\nAttributeError: 'ListColumn' object has no attribute 'binary_operator'\r\n```\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\nimport cudf\r\n\r\nseries1 = cudf.Series({1: [10, 20, 30]})\r\nseries2 = cudf.Series({1: [10, 20, 30]})\r\n\r\nseries1.equals(series2)\r\n```\r\n\r\n**Expected behaviour**\r\nNo error message. It works with DataFrames instead:\r\n\r\n```\r\nimport cudf\r\n\r\ndf1 = cudf.DataFrame({1: [10, 20, 30], 2: [20, 30, 40]})\r\ndf2 = cudf.DataFrame({1: [10, 20, 30], 2: [20, 30, 40]})\r\n\r\ndf1.equals(df2)\r\n```\r\n\r\n**Environment overview (please complete the following information)**\r\nDGX1\r\n\r\n**Environment details**\r\ncuDF version:  0.15.0a+4666.g1778921b0\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/6040/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/6040/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}