{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/7602",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/7602/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/7602/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/7602/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/7602",
    "id": 832190295,
    "node_id": "MDU6SXNzdWU4MzIxOTAyOTU=",
    "number": 7602,
    "title": "[BUG] dask_cudf generates files it cannot read back",
    "user": {
        "login": "lmeyerov",
        "id": 4249447,
        "node_id": "MDQ6VXNlcjQyNDk0NDc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4249447?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lmeyerov",
        "html_url": "https://github.com/lmeyerov",
        "followers_url": "https://api.github.com/users/lmeyerov/followers",
        "following_url": "https://api.github.com/users/lmeyerov/following{/other_user}",
        "gists_url": "https://api.github.com/users/lmeyerov/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lmeyerov/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lmeyerov/subscriptions",
        "organizations_url": "https://api.github.com/users/lmeyerov/orgs",
        "repos_url": "https://api.github.com/users/lmeyerov/repos",
        "events_url": "https://api.github.com/users/lmeyerov/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lmeyerov/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1139740666,
            "node_id": "MDU6TGFiZWwxMTM5NzQwNjY2",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/libcudf",
            "name": "libcudf",
            "color": "c5def5",
            "default": false,
            "description": "Affects libcudf (C++/CUDA) code."
        },
        {
            "id": 1185244142,
            "node_id": "MDU6TGFiZWwxMTg1MjQ0MTQy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/cuIO",
            "name": "cuIO",
            "color": "fef2c0",
            "default": false,
            "description": "cuIO issue"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
        "login": "vuule",
        "id": 16005690,
        "node_id": "MDQ6VXNlcjE2MDA1Njkw",
        "avatar_url": "https://avatars.githubusercontent.com/u/16005690?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vuule",
        "html_url": "https://github.com/vuule",
        "followers_url": "https://api.github.com/users/vuule/followers",
        "following_url": "https://api.github.com/users/vuule/following{/other_user}",
        "gists_url": "https://api.github.com/users/vuule/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/vuule/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vuule/subscriptions",
        "organizations_url": "https://api.github.com/users/vuule/orgs",
        "repos_url": "https://api.github.com/users/vuule/repos",
        "events_url": "https://api.github.com/users/vuule/events{/privacy}",
        "received_events_url": "https://api.github.com/users/vuule/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "vuule",
            "id": 16005690,
            "node_id": "MDQ6VXNlcjE2MDA1Njkw",
            "avatar_url": "https://avatars.githubusercontent.com/u/16005690?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vuule",
            "html_url": "https://github.com/vuule",
            "followers_url": "https://api.github.com/users/vuule/followers",
            "following_url": "https://api.github.com/users/vuule/following{/other_user}",
            "gists_url": "https://api.github.com/users/vuule/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vuule/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vuule/subscriptions",
            "organizations_url": "https://api.github.com/users/vuule/orgs",
            "repos_url": "https://api.github.com/users/vuule/repos",
            "events_url": "https://api.github.com/users/vuule/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vuule/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "milestone": null,
    "comments": 9,
    "created_at": "2021-03-15T21:02:56Z",
    "updated_at": "2024-02-23T18:43:06Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\n\r\nSomewhere between `dgdf = dask_cudf.read_csv(..)` and `dgdf.to_parquet()`, the generated files are written in a way that `cudf.read_parquet` and `dask_cudf.read_parquet` will fail to read the data back.\r\n\r\nException:  `cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1607621803079/work/cpp/src/io/parquet/reader_impl.cu:371: All sources must have the same schemas`\r\n\r\n\r\n\r\n**Steps/Code to reproduce bug**\r\n\r\nMay need to fix paths:\r\n\r\nDownload:\r\n\r\n```bash\r\ncurl -O /tmp/logs.csv.gz \"https://s3.amazonaws.com/botsdataset/botsv1/csv-by-sourcetype/botsv1.WinEventLog%3ASecurity.csv.gz\"\r\n(cd /tmp && gunzip logs.csv.gz)\r\n```\r\n\r\nConvert:\r\n```python\r\nwith dask.distributed.Client(ADDRESS):\r\n  dgdf = dask_cudf.read_csv('/tmp/logs.csv')\r\n  dgdf.to_parquet(\r\n       '/tmp/logs.parquet',\r\n        compression='snappy',\r\n        write_index=False,\r\n        index=False)\r\n```\r\n\r\nTest: Unexpectedly throws exn\r\n```python\r\ncudf.read_parquet('/tmp/logs.parquet')\r\n```\r\n\r\n**Expected behavior**\r\nThe converted file to read back with matching dtypes... but throws an exn\r\n\r\n**Environment overview (please complete the following information)**\r\nRAPIDS 0.18 (conda) in docker (ubuntu); A100's\r\n\r\n**Additional context**\r\n\r\n* Variants where we set `schema`, `dtypes`,  and `use_pandas_metadata` also fail\r\n* Also seeing failures when doing dask_cudf.read_parquet, and doing an intermediate repartition\r\n",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/7602/reactions",
        "total_count": 1,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 1
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/7602/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}