{
    "url": "https://api.github.com/repos/rapidsai/cudf/issues/6505",
    "repository_url": "https://api.github.com/repos/rapidsai/cudf",
    "labels_url": "https://api.github.com/repos/rapidsai/cudf/issues/6505/labels{/name}",
    "comments_url": "https://api.github.com/repos/rapidsai/cudf/issues/6505/comments",
    "events_url": "https://api.github.com/repos/rapidsai/cudf/issues/6505/events",
    "html_url": "https://github.com/rapidsai/cudf/issues/6505",
    "id": 719699661,
    "node_id": "MDU6SXNzdWU3MTk2OTk2NjE=",
    "number": 6505,
    "title": "[BUG] Reading JSON file saved from Series fails",
    "user": {
        "login": "drabastomek",
        "id": 3249948,
        "node_id": "MDQ6VXNlcjMyNDk5NDg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3249948?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/drabastomek",
        "html_url": "https://github.com/drabastomek",
        "followers_url": "https://api.github.com/users/drabastomek/followers",
        "following_url": "https://api.github.com/users/drabastomek/following{/other_user}",
        "gists_url": "https://api.github.com/users/drabastomek/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/drabastomek/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/drabastomek/subscriptions",
        "organizations_url": "https://api.github.com/users/drabastomek/orgs",
        "repos_url": "https://api.github.com/users/drabastomek/repos",
        "events_url": "https://api.github.com/users/drabastomek/events{/privacy}",
        "received_events_url": "https://api.github.com/users/drabastomek/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 599626559,
            "node_id": "MDU6TGFiZWw1OTk2MjY1NTk=",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 1139740666,
            "node_id": "MDU6TGFiZWwxMTM5NzQwNjY2",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/libcudf",
            "name": "libcudf",
            "color": "c5def5",
            "default": false,
            "description": "Affects libcudf (C++/CUDA) code."
        },
        {
            "id": 1139741213,
            "node_id": "MDU6TGFiZWwxMTM5NzQxMjEz",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/Python",
            "name": "Python",
            "color": "1d76db",
            "default": false,
            "description": "Affects Python cuDF API."
        },
        {
            "id": 1185244142,
            "node_id": "MDU6TGFiZWwxMTg1MjQ0MTQy",
            "url": "https://api.github.com/repos/rapidsai/cudf/labels/cuIO",
            "name": "cuIO",
            "color": "fef2c0",
            "default": false,
            "description": "cuIO issue"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 8,
    "created_at": "2020-10-12T22:07:00Z",
    "updated_at": "2024-05-21T00:26:32Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "**Describe the bug**\r\nReading a JSON file created from a Series `.to_json(path, orient='records', lines=True)` call leads to a `Input data is not a valid JSON file` when trying to read with `.read_json(path, orient='records', lines=True)` (with or without `engine='cudf'` parameter).\r\n\r\n**NOTE**: this is only a problem when saving Series in this format -- DataFrame objects are saved properly.\r\n\r\n**Steps/Code to reproduce bug**\r\n```\r\ncudf.Series([1,2,3,4,5]).to_json('sample.json', lines=True, orient='records')\r\n\r\ncudf.read_json('sample.json', lines=True, orient='records')\r\n```\r\n\r\nThe output file looks as follows:\r\n\r\n```\r\n1\r\n2\r\n3\r\n4\r\n5\r\n```\r\n\r\n**Expected behavior**\r\nThe file is read back properly and produces a valid `cudf.Series` object. \r\n\r\n**Environment overview (please complete the following information)**\r\n - Environment location: Docker\r\n - Method of cuDF install: Docker\r\n   - RAPIDS v 0.16 pull from nightly. ",
    "closed_by": null,
    "reactions": {
        "url": "https://api.github.com/repos/rapidsai/cudf/issues/6505/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/rapidsai/cudf/issues/6505/timeline",
    "performed_via_github_app": null,
    "state_reason": null
}